#!/bin/bash
# Setup HP OmniBook X - Current Best Method
# Since SSH is not yet enabled, uses standalone script approach

HP_IP="192.168.132.68"

echo "=========================================="
echo "HP OmniBook X Setup (IP: $HP_IP)"
echo "=========================================="
echo ""

# Check if standalone script exists
if [ ! -f "hp_local_setup.sh" ]; then
    echo "Creating standalone setup script..."
    ./setup/auto_setup_hp.sh
fi

echo "✅ Standalone setup script ready: hp_local_setup.sh"
echo ""
echo "=========================================="
echo "Setup Instructions"
echo "=========================================="
echo ""
echo "Since SSH is not yet enabled on HP, use the standalone script:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Copy Script to HP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A: Using SCP (if you have another way to access HP):"
echo "  scp hp_local_setup.sh <username>@$HP_IP:~/"
echo ""
echo "Option B: Using USB drive or network share:"
echo "  1. Copy hp_local_setup.sh to USB drive"
echo "  2. Plug USB into HP OmniBook X"
echo "  3. Copy file to HP home directory"
echo ""
echo "Option C: Email or cloud storage:"
echo "  1. Upload hp_local_setup.sh to cloud (Google Drive, Dropbox, etc.)"
echo "  2. Download on HP OmniBook X"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Run Setup on HP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "On HP OmniBook X, open terminal and run:"
echo ""
echo "  bash hp_local_setup.sh"
echo ""
echo "This will:"
echo "  ✅ Clone NAE repository"
echo "  ✅ Configure environment (PRODUCTION=true)"
echo "  ✅ Initialize safety systems"
echo "  ✅ Configure as Node"
echo "  ✅ Create production branch"
echo "  ✅ Enable SSH"
echo "  ✅ Show HP IP address"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Connect from Mac"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After HP setup completes, on Mac:"
echo ""
echo "  1. Get HP username from setup output"
echo "  2. Run: ./setup/configure_remote_connection.sh"
echo "     (Enter HP IP: $HP_IP)"
echo "     (Enter HP username)"
echo ""
echo "  3. Copy SSH key:"
echo "     ssh-copy-id <username>@$HP_IP"
echo ""
echo "  4. Test connection:"
echo "     ./setup/quick_connect.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Alternative: Direct Setup on HP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If you prefer to set up directly on HP:"
echo ""
echo "  git clone https://github.com/cbjones84/NAE.git"
echo "  cd NAE"
echo "  bash setup/automated_hp_setup.sh"
echo ""
echo "=========================================="
echo ""
echo "Standalone script location:"
echo "  $(pwd)/hp_local_setup.sh"
echo ""
echo "File size: $(du -h hp_local_setup.sh | cut -f1)"
echo ""
echo "Master API Key (for reference):"
echo "  72364bc8ecfea124010e9811d06d0b0b3b220e4dee3d09163b2bd1f005af40a7"
echo ""

